# Generated by Django 3.2 on 2021-04-20 06:28

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='img/%y')),
                ('details', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=150)),
                ('twitter', models.URLField(max_length=350)),
                ('facebook', models.URLField(max_length=350)),
                ('linkdin', models.URLField(max_length=350)),
                ('github', models.URLField(max_length=350)),
                ('stack_overflow', models.URLField(max_length=350)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('image', models.ImageField(upload_to='article/%y')),
                ('published', models.DateTimeField(auto_now=True)),
                ('body', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=250, null=True, unique=True)),
                ('unique_id', models.CharField(max_length=100, unique=True)),
                ('artcle_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_blog.author')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_blog.category')),
            ],
        ),
    ]
