# Generated by Django 3.2 on 2021-04-20 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_blog', '0003_alter_article_unique_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='About_Me',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='img/%y')),
                ('name_1', models.CharField(max_length=20)),
                ('name_2', models.CharField(max_length=20)),
                ('phone_1', models.CharField(max_length=20)),
                ('phone_2', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=150)),
                ('details', models.TextField()),
                ('twitter', models.URLField(max_length=350)),
                ('facebook', models.URLField(max_length=350)),
                ('linkdin', models.URLField(max_length=350)),
                ('github', models.URLField(max_length=350)),
                ('stack_overflow', models.URLField(max_length=350)),
                ('resume', models.FileField(upload_to='documents')),
            ],
        ),
    ]
