# Generated by Django 3.2 on 2021-04-20 08:40

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_blog', '0004_about_me'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about_me',
            name='details',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
