# Generated by Django 3.1.5 on 2021-04-25 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_blog', '0006_auto_20210425_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(default=1, upload_to='article/%y'),
            preserve_default=False,
        ),
    ]
